### PR TITLE
add mtef3 support

### PR DESCRIPTION
**Pull request by sbulka**
* Created submodules Mathtype3 and Mathype5.
* Calls from outside can still use Mathtype::Converter as before.
* Mathtype::Converter will throw NotImplementedError if mtef version is not 3 or 5.

### CODE REVIEW

**Comment by jure** [comment]
Thank you for this PR, looks good! One question, how different are the records between MTEF 3 and MTEF 5? Could some of those records be deduplicated or are there differences everywhere?

**Comment by sbulka** [comment]
The way options are handled is different beetween MTEF 3 and 5.
Would need to write an individual BinData type for options which parses them the right way, then most records could be unified I think.

**Comment by jure** [comment]
Thank you for your contributions @sbulka, this looks like you're adding amazing value to the project! I still have that concern of code duplication between MTEF 3 and MTEF 5. If you can somehow address that, I would merge this straight away (and then further contributions can be more granular).

**Comment by sbulka** [comment]
Just found some time to work on the "easy-to-merge" classes.  
Unfortunately still needs some more work on classes where the options have to be handled differently.

Btw. its possible I encounter some .eps and .gif files in the upcoming weeks, so will likely add support for those too.

**Comment by jure** [comment]
Absolutely fantastic, @sbulka! I'd be OK with abstracting only virtually identical classes. If there are situations where it's tricky to abstract the different handling of options, I say we keep those separated and not worry about it.

If you can resolve the new merge conflicts (sorry, it's an inline/block fix that arrived in master in the mean time), I'll merge this straight away.

**Comment by sbulka** [comment]
Passes tests now.  
I want to keep features more branch-separated, so future PR can be accepted easier.  
Thank you for your effort too! :)

On the remaining separate classes:  
Hardest part to refactor is the Payload class, because it requires some 'default' choices.  
Didn't get the way to extend these choices in subclasse, yet.  
The remaining classes depend on that in some way, but should then be an easy thing to do.

**Comment by jure** [comment]
Awesome, thank you for your contribution! 👍

**Comment by jure** [comment]
@sbulka Mathtype 0.1.0 has been released: https://rubygems.org/gems/mathtype 🎉

**Pull request merged**
